const appActions = {
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  SET_REDUXREADY: 'SET_REDUXREADY',
  HANDLE_LOADER: 'HANDLE_LOADER'
};

const userActions = {
  LOGIN_USER:"LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  RESET_USER: "RESET_USER",
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_COMPLETE: "AUTH_COMPLETE",
  SAVE_USER_DATA: "SAVE_USER_DATA"
};

const devicesActions = {
  ADD_DEVICES:"ADD_DEVICES",
  APPEND_DEVICES:"APPEND_DEVICES",
  SAVE_CLICKED_DEVICE_DATA: "SAVE_CLICKED_DEVICE_DATA",
  SET_PARTICULAR_ATTRIBUTE_DATA: "SET_PARTICULAR_ATTRIBUTE_DATA"
};




const Types = {
  ...appActions,
  ...userActions,
  ...devicesActions
};

export default Types;
